#!/bin/bash
export NVIM_LISTEN_ADDRESS=/tmp/nvimsocket
SVIM="ON"
if [ ! $(pgrep nvim) ]
     then 
	     if [ -z "$@" ] ; then
			alacritty --title "svim" -e nvim -u ~/.config/nvim/restore.vim
		else
	     		alacritty --title "svim" -e nvr "$@"
	    		echo "no serverlist"
		fi
     else
	     nvr --remote "$@"
	     wmctrl -a svim
	     echo "server is running"
fi
